// Regenerates src/core/iso-data.ts from i18n-iso-countries (MIT).
// Run: node scripts/generate-iso.mjs
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const countries = require("i18n-iso-countries");

const alpha2Codes = Object.keys(countries.getAlpha2Codes()).sort();
const rows = alpha2Codes.map((alpha2) => {
  const alpha3 = countries.alpha2ToAlpha3(alpha2);
  const numeric = countries.alpha2ToNumeric(alpha2);
  const name = countries.getName(alpha2, "en");
  if (!alpha3 || !numeric || !name) throw new Error(`incomplete row for ${alpha2}`);
  return `  ["${alpha2}", "${alpha3}", "${numeric}", ${JSON.stringify(name)}],`;
});

const out = `// Generated by scripts/generate-iso.mjs from i18n-iso-countries — do not edit by hand.
// ISO 3166-1: [alpha2, alpha3, numeric, English short name].
export type IsoRow = readonly [alpha2: string, alpha3: string, numeric: string, name: string];

export const ISO_3166_1: readonly IsoRow[] = [
${rows.join("\n")}
];
`;

const dest = join(dirname(fileURLToPath(import.meta.url)), "../src/core/iso-data.ts");
writeFileSync(dest, out);
console.log(`wrote ${rows.length} rows to ${dest}`);
